id: taxonomy_term.full
uuid: 569e54aa-cf5f-4369-b100-ade8d8a371bd
label: 'Taxonomy term page'
targetEntityType: taxonomy_term
status: true
cache: true
langcode: und
dependencies:
  module:
    - taxonomy
